name: ant_design_flutter
description: A Flutter UI framework designed for web / pc application, contains some high quality widgets.
version: 0.0.1+5
homepage: https://doc.antdf.xyz
repository: https://github.com/CalsRanna/ant_design_flutter

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
