name: ant_design_flutter
description: An UI framework designed for Flutter.
version: 0.0.1
homepage: http://doc.antdf.xyz

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
